"""empty message

Revision ID: 6984a641cfbf
Revises: 8003efb6bc1d
Create Date: 2024-03-18 23:37:43.025064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6984a641cfbf'
down_revision = '8003efb6bc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service1', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('service2', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('short_description', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('long_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=256), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('delivery_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=True)
        batch_op.alter_column('years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('gender')
        batch_op.drop_column('service')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('years_of_experience',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('delivery_time',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.String(length=128),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('image')
        batch_op.drop_column('long_description')
        batch_op.drop_column('short_description')
        batch_op.drop_column('service2')
        batch_op.drop_column('service1')

    # ### end Alembic commands ###
