"""empty message

Revision ID: 8003efb6bc1d
Revises: dce7a13d365d
Create Date: 2024-03-16 06:03:29.470046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8003efb6bc1d'
down_revision = 'dce7a13d365d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reviews', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('delivery_time', sa.String(length=50), nullable=False),
    sa.Column('top_rated', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor')
    # ### end Alembic commands ###
